/*
 * MainUI.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import dialog.LoginCwqUI;
import system.Config;
import utils.FrameUtil;
import utils.LoginListener;

/**
 *
 * @author  __USER__
 */
public class MainUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** Creates new form MainUI */
	public MainUI() {
		initComponents();
		FrameUtil.initWindows(this);

	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPopupMenu1 = new javax.swing.JPopupMenu();
		jPopupMenu2 = new javax.swing.JPopupMenu();
		jFileChooser1 = new javax.swing.JFileChooser();
		jFrame1 = new javax.swing.JFrame();
		jp_content = new javax.swing.JPanel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
		jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenu5 = new javax.swing.JMenu();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();
		jMenu4 = new javax.swing.JMenu();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenuItem7 = new javax.swing.JMenuItem();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jp_content.setLayout(new java.awt.GridBagLayout());

		jMenu3.setText("\u7cfb\u7edf");
		jMenu3.setFont(new java.awt.Font("黑体", 0, 14));

		jCheckBoxMenuItem1.setFont(new java.awt.Font("黑体", 0, 12));
		jCheckBoxMenuItem1.setText("\u767b\u5f55\u57ce\u5916\u5708");
		jCheckBoxMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jCheckBoxMenuItem1MouseClicked(evt);
			}
		});
		jCheckBoxMenuItem1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jCheckBoxMenuItem1ActionPerformed(evt);
					}
				});
		jMenu3.add(jCheckBoxMenuItem1);

		jCheckBoxMenuItem2.setFont(new java.awt.Font("黑体", 0, 12));
		jCheckBoxMenuItem2.setSelected(true);
		jCheckBoxMenuItem2.setText("\u767b\u5f55\u5fae\u535a\u6613");
		jCheckBoxMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jCheckBoxMenuItem2MouseClicked(evt);
			}
		});
		jMenu3.add(jCheckBoxMenuItem2);

		jMenuBar1.add(jMenu3);

		jMenu2.setText("\u5fae\u535a");
		jMenu2.setFont(new java.awt.Font("黑体", 0, 14));

		jMenuItem3.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem3.setText("\u57ce\u5916\u5708");
		jMenu2.add(jMenuItem3);

		jMenuItem4.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem4.setText("\u5fae\u535a\u6613");
		jMenu2.add(jMenuItem4);

		jMenuBar1.add(jMenu2);

		jMenu1.setText("\u5fae\u4fe1");
		jMenu1.setFont(new java.awt.Font("黑体", 0, 14));

		jMenuItem1.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem1.setText("\u57ce\u5916\u5708");
		jMenu1.add(jMenuItem1);

		jMenuItem2.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem2.setText("\u5fae\u535a\u6613");
		jMenu1.add(jMenuItem2);

		jMenuBar1.add(jMenu1);

		jMenu5.setText("\u670b\u53cb\u5708");
		jMenu5.setFont(new java.awt.Font("黑体", 0, 14));

		jMenuItem8.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem8.setText("\u57ce\u5916\u5708");
		jMenu5.add(jMenuItem8);

		jMenuItem9.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem9.setText("\u5fae\u535a\u6613");
		jMenu5.add(jMenuItem9);

		jMenuBar1.add(jMenu5);

		jMenu4.setText("\u8bbe\u7f6e");
		jMenu4.setFont(new java.awt.Font("黑体", 0, 14));

		jMenuItem5.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem5.setText("\u5fae\u4fe1\u6570\u636e\u6e90");
		jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenuItem5MouseClicked(evt);
			}
		});
		jMenuItem5.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				jMenuItem5ItemStateChanged(evt);
			}
		});
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem5);

		jMenuItem6.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem6.setText("\u5fae\u535a\u6570\u636e\u6e90");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem6);

		jMenuItem7.setFont(new java.awt.Font("黑体", 0, 12));
		jMenuItem7.setText("\u65e5\u5fd7\u6587\u4ef6\u5939");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu4.add(jMenuItem7);

		jMenuBar1.add(jMenu4);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_content, javax.swing.GroupLayout.DEFAULT_SIZE, 399,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jp_content, javax.swing.GroupLayout.DEFAULT_SIZE, 209,
				Short.MAX_VALUE));
		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jCheckBoxMenuItem1ActionPerformed(
			java.awt.event.ActionEvent evt) {
		if(loginUI == null) {
			loginUI = new LoginCwqUI();
		}
		this.setFocusable(false);
		loginUI.setVisible(true);
		loginUI.setLoginListener(new LoginListener() {
			
			@Override
			public void onSuccess() {
				MainUI.this.setVisible(true);
				System.out.println("on success");
			}
			
			@Override
			public void onFailed() {
				System.out.println("fail");
				MainUI.this.setVisible(true);
			}
		});
	}

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser chooser = new JFileChooser();
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		chooser.showDialog(this, "选择");
		File file = chooser.getSelectedFile();
		if (file == null) {
			return;
		}
		Config.getInstance().PATH_LOG = file.getAbsolutePath();
		try {
			Config.getInstance().saveConfig();
		} catch (IOException e) {
			System.out.println("保存配置失败");
		}
	}

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser chooser = new JFileChooser();
		chooser.showDialog(this, "选择");
		File file = chooser.getSelectedFile();
		if (file == null) {
			return;
		}
		Config.getInstance().PATH_WEIBO = file.getAbsolutePath();
		try {
			Config.getInstance().saveConfig();
		} catch (IOException e) {
			System.out.println("保存配置失败");
		}
	}

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser chooser = new JFileChooser();
		chooser.showDialog(this, "选择");
		File file = chooser.getSelectedFile();
		if (file == null) {
			return;
		}
		Config.getInstance().PATH_WEIXIN = file.getAbsolutePath();
		try {
			Config.getInstance().saveConfig();
		} catch (IOException e) {
			System.out.println("保存配置失败");
		}
	}

	private void jMenuItem5ItemStateChanged(java.awt.event.ItemEvent evt) {

	}

	private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {
		System.out.println("hahah");

		//		file.show();
	}

	private void jCheckBoxMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {

	}

	private void jCheckBoxMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainUI().setVisible(true);
				try {
					Config.getInstance().init();
					Config.getInstance().PATH_LOG = "c:\\hhhhh";
					Config.getInstance().saveConfig();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	private javax.swing.JPopupMenu jPopupMenu1;
	private javax.swing.JPopupMenu jPopupMenu2;
	private javax.swing.JPanel jp_content;
	// End of variables declaration//GEN-END:variables
	
	private LoginCwqUI loginUI; 

}